### ISSUE TITLE
Small images in mobile layout doesn’t look elegant 

### ISSUE THREAD

**Issue by osdiab** [everydotorg/donate-button#101]
The split panel looks great but the tiny boxes with the image in it doesn’t look as cool - interested in brainstorming a bit how we can make a really beautiful version for the mobile flow

![D32739EB-04DA-4746-A526-1FBFF23001D8](https://user-images.githubusercontent.com/1890926/107518993-0466c100-6bf3-11eb-95c5-b0b7868af96d.png)
E

**Comment by martinbianchi** [comment]
should we close this?

**Comment by micamastro** [comment]
I think it's fixed in #116 PR, right?

**Comment by osdiab** [comment]
i think there is a bigger design rehaul of how we want to display the donate button (#86 , our conversation on the last p22 sync with @jake-nz and oliver). but perhaps that can all be part of a bigger design rework as opposed to this individual task, can close and i'll just keep in touch with them directly.
