### ISSUE TITLE
Switch to TypeScript?

### ISSUE THREAD

**Issue by osdiab** [everydotorg/donate-button#11]
Throwing this out since other Every.org code is all in TypeScript and a switch to it would be pretty simple for me to implement. Is P22 team open to that @jake-nz ?

**Comment by osdiab** [comment]
I'd like to do this, the way that configuration is working now is leading to all sorts of undefined access errors, which wouldn't exist in a proper typescript codebase. i'll do a migration; if that's fine with you @jake-nz !

**Comment by jake-nz** [comment]
Yep! We like Typescript:)

**Comment by osdiab** [comment]
Sweet, I'll have a PR out for it soon :)
