### ISSUE TITLE
Demo split layout doesn't work - Serve demo from Vercel

### ISSUE THREAD

**Issue by markulrich** [everydotorg/donate-button#123]
At https://assets.every.org/donate-button-v2/ if I hit "show configured split layout" nothing happens. For now updated Readme to show example of the real thing with https://github.com/everydotorg/donate-button/commit/e884ceb0a2facb5332bf41b0a0284e2de76d74e7

**Comment by martinbianchi** [comment]
Is possible that the link is not updated with the latest changes? For example this [preview deployed by vercel](https://donate-button-git-mbianchi-generic-button-everydotorg.vercel.app/) that it's from an active PR seems to be working.

I think that we had a similar issue in the past and it was fixed

**Comment by osdiab** [comment]
yeah interesting, alternatively we can just make the demo link go to vercel instead of to this `assets.every.org` link, and assign a subdomain to it (e.g. `donate-button.every.org`). let's go wiht that

**Comment by osdiab** [comment]
actually yeah we can just change it to https://donate-button.vercel.app/ and it works already.

**Comment by osdiab** [comment]
OK it's being served from embeds.every.org. I'll add that to the docs!
