### ISSUE TITLE
RFC: support staging environment

### ISSUE THREAD

**Issue by osdiab** [everydotorg/donate-button#125]
We can support trying out teh donate button on a staging environment by switching the `www.every.org` to `staging.every.org`, but i worry taht including such a flag will ultimately result in a nonprofit accidentlly pushing the staging version to prod. think we should expose this functionality? @markulrich

**Comment by osdiab** [comment]
Let’s not do it for now until we have some obvious banner on the site that you’re using staging when you come in with a donate button.

**Comment by markulrich** [comment]
Seems low priority, I wouldn't add any complications to the set-up

**Comment by osdiab** [comment]
closing this for now then!
