### ISSUE TITLE
Support opening the donation flow in a new tab

### ISSUE THREAD

**Issue by osdiab** [everydotorg/donate-button#126]
Right now we open the donation flow in the same tab as the page the button is embedded on. But some referrers like GiveBlck want to open it in a new tab instead; i think this is a reasonable request, let's add it in.

**Comment by osdiab** [comment]
If you have time to do this @martinbianchi lmk, urgent for a partner - but if not I'll handle it when I wake up tomorrow. Thanks!

**Comment by martinbianchi** [comment]
@osdiab Sorry, I've just seen this. I created a PR to support it.
Do you think that the approach is ok? Or we should encapsulate  and simplify the option for something like:
`openFlowInANewPage: boolean` or something like that?

**Comment by osdiab** [comment]
I think just a boolean is simpler!

**Comment by osdiab** [comment]
implemented it!
