### ISSUE TITLE
New Widget - Country selector

### ISSUE THREAD

**Issue by micamastro** [everydotorg/donate-button#157]
Third option user should select is the country.
**`This country selector is optional, and will be something turned on/off by the nonprofit.`**

### With country selector
By default it should display a country chosen by the nonprofit.
![image](https://user-images.githubusercontent.com/36522634/117473193-1032fc80-af30-11eb-94ad-9d79a3238678.png)

If users click on that box, then they should be able to change the country.
Each country contains: flag, name of the country, text and available payment methods
![image](https://user-images.githubusercontent.com/36522634/117474016-efb77200-af30-11eb-9afb-d206253550e7.png)

Selecting one of this should return to the widget homepage with the country selected.

### Without country selector
![image](https://user-images.githubusercontent.com/36522634/117475917-f941d980-af32-11eb-8918-b696e10c3b69.png)

**Comment by micamastro** [comment]
Hi @osdiab one question here, can we pull this countries from Every or is something that the non-profit should provide?

**Comment by osdiab** [comment]
It's not implemented yet, but eventually we will return the country with the nonprofit; You can currently get the nonprofit data from this URL:

```
GET "https://www.every.org/api/nonprofits/:nonprofitSlug

**Comment by martinbianchi** [comment]
@osdiab we are getting a CORS error. Do we need an api key or something?

**Comment by osdiab** [comment]
Ah yeah looks like there is a CORS restriction. Will get back to you with a solution.
