### ISSUE TITLE
Giveli.st > Pull the nonprofit profiles from Every

### ISSUE THREAD

**Issue by micamastro** [everydotorg/donate-button#178]
Create a test link that pulls the nonprofit profiles from Every.org and links the donation to their payment flow

**Comment by martinbianchi** [comment]
@osdiab Do you have an API to get the information of each active campaign which the corresponding nonprofits information to show on the givelist flow?

**Comment by osdiab** [comment]
We do internally and i'll also add that to the third party API that can be accessed outside of our site!
