### ISSUE TITLE
New Widget > Data pulled from Every

### ISSUE THREAD

**Issue by micamastro** [everydotorg/donate-button#188]
- [x] Message that invites you to donate -- Not sure if this is currently stored in Every
This message:
![image](https://user-images.githubusercontent.com/36522634/119852407-a762f280-bee5-11eb-894c-16d6cd18eb45.png)

- [x] Nonprofit's logo
- [x] Background image
- [ ] List of countries
- [ ] Currencies available for each country
- [ ] Payments methods for each country

**Comment by osdiab** [comment]
OK, you can get tons of info about the nonprofits like so:

```
fetch("https://partners.every.org/v0.2/nonprofit/maps")
```

It should work regardless of CORS. Let me know if that works for you guys!

**Comment by osdiab** [comment]
The currencies and payment methods for each country is still in the works, but it will show up there once the code for it has been deployed.

**Comment by micamastro** [comment]
Hey @osdiab please, let us know when the currencies and payment methods have been included in the api.
Thanks! :)
