### ISSUE TITLE
Giveli.st > Amount of total donation and givers

### ISSUE THREAD

**Issue by micamastro** [everydotorg/donate-button#190]
We need to get from Every the current amount donated to the list and the current number of donors.

We need this to appear as information before the person donates.
![image](https://user-images.githubusercontent.com/36522634/120208446-db028d00-c203-11eb-85f5-f1632c84e788.png)

and after the person donates with updated data:
![image](https://user-images.githubusercontent.com/36522634/120208464-e35ac800-c203-11eb-9f32-bf9eb195bf0f.png)

**Comment by osdiab** [comment]
Let me get back to you on how this can work—we currently do this for pages like https://www.every.org/@timferriss/questbridge , sending back the amount raised by follow up donations to a particular nonprofit.

We chatted with Ed and Ollie earlier today and we're planning on using a "fund" nonprofit to handle givelist funds initially - but later on that may change to use a more flexible "giving basket" type of functionality. So in the meantime we can expose and endpoint for those funds, but we need to think a bit about how it would work if we do the "giving basket" approach. 

cc @markulrich
