### ISSUE TITLE
Better css if there is no country

### ISSUE THREAD

**Issue by markulrich** [everydotorg/donate-button#250]
See https://embeds.every.org/0.3 for LiveBetter, when there is no country option the spacing on the left feels a bit off with a large empty white space

![image](https://user-images.githubusercontent.com/6357579/132560289-8944b7a9-c9f4-4f22-a05a-7fd3eacfdeea.png)

**Comment by micamastro** [comment]
This should be better in the new designs:
Without country
![image](https://user-images.githubusercontent.com/36522634/136081075-1d31c978-95f4-4a57-9e0e-88d4d61fb874.png)

With country
![image](https://user-images.githubusercontent.com/36522634/136081192-b33ce699-834b-49a1-ae0b-6488a929d1b7.png)
