### ISSUE TITLE
Increase tap target for currency selector

### ISSUE THREAD

**Issue by markulrich** [everydotorg/donate-button#254]
In the amount bar the currency selector has a very small tap target. And perhaps text could be larger?

![image](https://user-images.githubusercontent.com/6357579/134713888-385a4271-9a7a-4033-be58-5fc57908bee7.png)

**Comment by micamastro** [comment]
Sure! We'll add that change together with the new widget designs if that's ok with you @markulrich 
We plan to finish the new layout by the end of this week or early next week. If you need to have this change before we can edit the current widget
