### ISSUE TITLE
Multiple donate buttons on the same page breaks

### ISSUE THREAD

**Issue by rahulgi** [everydotorg/donate-button#302]
See https://everydotorg.slack.com/archives/C019X7TUTTL/p1642187463028400

Having a donate button and crypto button on the same page causes the first button to break, b/c the `onload` gets overridden by the second button.

Swapping `onload = ` with `addEventListener("load", createWidget)` solves the issue, but I think it could it result in the initialization function being called many times if someone copy-pastes our code for buttons many times on the page. That being said, running the initialization code again doesn't seem to cause any problems, so maybe it's not an issue?

Would using different class names for the different donate buttons be a better option?

**Comment by malsmr** [comment]
Is this ready to be worked on?
