### ISSUE TITLE
Automatic script injection breaks on Wordpress v6.2.2

### ISSUE THREAD

**Issue by markulrich** [everydotorg/donate-button#350]
We have been using the Fundraiser button for some time now without issue, but I believe the latest version of Wordpress has caused and incompatibility issue.

We first realized the website was throwing a critical styling error so we began troubleshooting by removing plugins and customizations 1 by 1. We realized the problem was coming from an external script tag in the <header>. Turns out the EveryOrg <script> tag which allows for the every.org embed was the root cause of the issue.

(<script async defer src="https://embeds.every.org/0.4/button.js" />)

We are very familiar with Wordpress and have in house developers, so we were able to reproduce the error on a fresh Wordpress install using various different methods.

Being that we were already using a plugin to insert scripts to the header and footer, we decided to try different plugins, and even decided to add the <script> tag directly to the header via the theme files which unfortunately still reproduced the same error. This leads us to believe the issue must lie here with the widget itself.

For reference we are updated to the latest versions of Wordpress v6.2.2, we reproduced the error on different themes (custom and default themes) with direct header injection along with various header script insert plugins. We also verified we were copying the links directly from the website and verifying our input.

**Comment by culturehives** [comment]
The issue has been resolved. Thanks @markulrich and @Fishbakh-N.

The `<script>` element requires both the starting and ending tags.

The updated solution is:
`<script async defer src="https://embeds.every.org/0.4/button.js"></script>`
