### ISSUE TITLE
Remove `.yarn/cache` from version control

### ISSUE THREAD

**Issue by flacial** [everydotorg/donate-button#381]
### Overview

While reviewing the codebase, I noticed that the `.yarn/cache` folder is getting tracked by the version control system and this folder contains a cache of all the packages installed using Yarn. This folder can get large quickly over time, making cloning/pulling from the repo slow. Caused by #363.

### Proposal

1. Add `.yarn/cache` to the `.gitignore` file
2. Remove the currently tracked folder `.yarn/cache` from the repo using `git rm -r --cached .yarn/cache`
   - [`--cached` will remove the file from the git repo but keep it in locally in the machine](https://git-scm.com/docs/git-rm#Documentation/git-rm.txt---cached)

---

I'll be more than happy to create a PR that applies the above proposal!

**Comment by malsmr** [comment]
Is this ticket ready to be picked up?

**Comment by rahulgi** [comment]
@flacial thanks for opening this ticket. We include the `.yarn/cache` folder intentionally (per the Offline Caching strategy recommended by yarn [here](https://yarnpkg.com/features/caching)). While it makes cloning the repo a bit slower (and you reduce that time by doing `git clone --depth=0` the first time you clone it, it also saves time when doing an initial `yarn install`. If you wanted to create a PR that updates the README to note that you can reduce the depth of the initial clone to download the repo faster, that would certainly be appreciated!
