### ISSUE TITLE
unreadable text when browsing in dark mode

### ISSUE THREAD

**Issue by andrewrk** [everydotorg/donate-button#384]
Hello Every.org team,

Thanks for your wonderful organization and for this handy widget. It's almost perfect for us except for a little CSS bug.

In this screenshot, it is difficult to see but I have typed "1000" into the Donation Amount box. You can see the problem live at https://ziglang.org/zsf/

![image](https://github.com/everydotorg/donate-button/assets/106511/9d8f5454-f3e5-4d8a-93b6-a5b7f5900c14)

In normal or light mode, which is the setting most users browse with, this is not a problem. But users who have their system theme set to dark mode will not be able to see the donation amount.

You can simulate this in Firefox with this button:

![image](https://github.com/everydotorg/donate-button/assets/106511/4fc6e4a6-bfe6-40b6-98d1-1b278b4181f5)

I've been trying to work around the issue but it's tricky because of the shadow DOM. I didn't know about the shadow DOM until today so I've been trying things like

```csss
#donation-input {
  color:black
}
```

and scratching my head as to why it wasn't taking effect.

This affects the "Private Note" field as well:

![image](https://github.com/everydotorg/donate-button/assets/106511/4842e6e4-47fe-4bed-8794-3f0f7360dcbd)

Any suggested workaround would be welcome.

**Comment by andrewrk** [comment]
Found a workaround:
```js
let style = document.createElement('style');
style.innerHTML = '#donation-input { color: black; } #privateNote { color: black }';
document.getElementById("shadow-wrapper").shadowRoot.appendChild(style);
```

**Comment by markulrich** [comment]
Thank you for reporting @andrewrk! It should be resolved by https://github.com/everydotorg/donate-button/pull/417
