### ISSUE TITLE
with embed js code, h2 h3 h4 h5 h6 CSS affects the rest of the page!

### ISSUE THREAD

**Issue by mab253** [everydotorg/donate-button#390]
it looks like this fix was rolled back recently, I am seeing the same selectors applied in my CSS!

```
.every-embedded-5bh1, h2, h3, h4, h5, h6 {
   font-weight: 700;
}
```

_Originally posted by @mab253 in https://github.com/everydotorg/donate-button/issues/374#issuecomment-1961972269_

**Comment by markulrich** [comment]
Thanks for reporting @mab253! I believe resolved by https://github.com/everydotorg/donate-button/pull/410
