### ISSUE TITLE
OnlyFurus embed didn't work

### ISSUE THREAD

**Issue by osdiab** [everydotorg/donate-button#51]
Not sure how they embedded it, but they ended up copying the code from our example to do it instead. Figure out why it screwed up.

**Comment by osdiab** [comment]
looks like the README is outdated

**Comment by osdiab** [comment]
The Cloudflare worker doesn't show any KV value for `onlyfurus`, so i would assume they tried to use the `assets.every.org/every-month/bundle.js`, which was the old version of the donate button (current one is `assets.every.org/donate-button-v2/*`).

If they were using the dynamic cloudflare assets, they would have gone to `assets.every.org/donate-button/{slug}/*` and a KV value would have been used.

**Comment by osdiab** [comment]
he says he used "the actual script used in the demo" - which i'm guessing means, he isn't using our `assets.every.org` CDN at all, it's getting whatever is the built version on the demo page, which isn't going through that URL. which should work i guess lol

**Comment by osdiab** [comment]
https://every-month.vercel.app/ pulls in https://every-month-bivnx293c.vercel.app/webComponent.js , which i'm pretty sure is old/outdated.

**Comment by osdiab** [comment]
cc @jake-nz

**Comment by osdiab** [comment]
i think the Vercel instance is not run by Every.org, it's P22's, so I don't have visibility into the actual build it's running.

**Comment by osdiab** [comment]
Nonetheless the trick is probably to update the README as per #52

**Comment by osdiab** [comment]
yup, checking the HTML on onlyfurus.com's NOPE page, that's the one they're using.

**Comment by osdiab** [comment]
It's possible that it going to one time instead of monthly is also a result of it being outdated.

**Comment by jake-nz** [comment]
Re Vercel: every-month.vercel.app is now connected to this repo

**Comment by markulrich** [comment]
The same bug appears at https://every-month.vercel.app/  - when you donate the link has `frequency=ONCE` instead of `frequency=MONTHLY`

**Comment by osdiab** [comment]
`webComponent.js` only appears to be in the old `every-month` folder, so yeah i would presume they're using an old version.

**Comment by jake-nz** [comment]
Sorry, Vercel has not been updated recently. See my comment here: https://github.com/everydotorg/donate-button/issues/54#issuecomment-770462423

**Comment by jake-nz** [comment]
#44 addresses the MONTHLY vs ONCE bug

**Comment by osdiab** [comment]
I landed #44 and pushed a new version to the Github pages.
