### ISSUE TITLE
Style issues on girlsintech.org

### ISSUE THREAD

**Issue by markulrich** [everydotorg/donate-button#57]
1. The default options feels like there is one missing - either let's add a fourth option $500 or make each option full-width same as when there are names for the different levels of support.
2. Scrolling feels quite strange, kinda like i'm still on the other page. There should be no scrollbar at all since everything can fit on my screen.

![image](https://user-images.githubusercontent.com/6357579/106424936-24360200-6407-11eb-945e-d69a6a25f8ad.png)

**Comment by osdiab** [comment]
we should probably be scroll locking the page like we do on the main `every.org` app.
