### ISSUE TITLE
Ffungi - One-time and monthly donation in separate buttons

### ISSUE THREAD

**Issue by micamastro** [everydotorg/donate-button#61]
WHEN I go to ffungi website
THEN the layout should be as the following:

Desktop
![image 6.jpg](https://images.zenhubusercontent.com/5f933b15ca94452ae3ee3bca/5fc86043-4356-4ddc-9d2d-f359b96ff5ee)
Note that everything should be centered now.

Mobile
![image.png](https://images.zenhubusercontent.com/5f933b15ca94452ae3ee3bca/7efa17e9-df8f-469f-9be2-546b8db9de94)
Note: please make sure we delete the label "international NGO" in mobile

AND the "donate" button on the header should open the widget in the one-time donation flow
AND the "donate monthy" should open the widget in the monthly flow

Spanish traslations for the buttons: 
Donate -> Donar
Donate Monthly -> Donar mensualmente

**Comment by martinbianchi** [comment]
Implemented after #70
