### ISSUE TITLE
Lock the scroll position when the modal is up

### ISSUE THREAD

**Issue by osdiab** [everydotorg/donate-button#79]
When it's not this happens:

https://app.usebubbles.com/q5ej4S1KZbGhmQzTjujxft/comments-on-girlsintech-org/

This can do it, it's super tiny in bundle size too.

https://www.npmjs.com/package/body-scroll-lock

**Comment by martinbianchi** [comment]
Is this currently happening? I uploaded a fix with #72. I see on the video that was recorded before the PR was merged.

**Comment by osdiab** [comment]
Ah yeah. Not on my phone but will double check some other browsers!

**Comment by osdiab** [comment]
great on modern browsers it seems fine, closing!
