### ISSUE TITLE
Allow for donate modal to use more horizontal space

### ISSUE THREAD

**Issue by osdiab** [everydotorg/donate-button#86]
The modal looks kinda skinny on a normal desktop browser when there's no split panel, which contributes to the modal tending to overflow vertically - there's a lot of screen real estate we could be using to fit things comfortably on the screen without going too wide.

Maybe we can adapt the design to have a two-column layout on a standard desktop browser screen size, and sidestep the need for making variations on styles for constrained height screens, if we make better use of the screen real estate available. not sure how it would impact the split panel though.

<img width="1241" alt="Screen Shot 2021-02-08 at 16 46 58" src="https://user-images.githubusercontent.com/1890926/107189839-552cbd00-6a2d-11eb-993e-79345d52bf0c.png">

**Comment by micamastro** [comment]
Hey @osdiab !

We are working on this new design to be sth like this:
![image](https://user-images.githubusercontent.com/36522634/111633867-b5551280-87d4-11eb-988d-3d9f354e3dea.png)

This is still WIP, but we'll let you know when we have more to show

**Comment by osdiab** [comment]
Looks great! Looking forward to finalizing it :)

**Comment by micamastro** [comment]
This will be fixed with the new widget layout (issues 154 to 161)
