### ISSUE TITLE
should not allow entering values less than $10

### ISSUE THREAD

**Issue by osdiab** [everydotorg/donate-button#88]
We don't support values less than $10, and our site apparently messes up without an error if you try to submit such a donation. we need validation to force larger donations.

**Comment by osdiab** [comment]
@martinbianchi thanks for taking this! In addition I found another invalid input: we don't allow decimal values. So this shouldn't allow inputting stuff like periods or letters.

**Comment by martinbianchi** [comment]
Cool! I will fix it too. Do you have a message in mind to show to the user in those cases?

**Comment by markulrich** [comment]
@martinbianchi please replicate behavior you see on pages like https://www.every.org/givewell/donate! I think for amounts under $10 the error message is "Amount must be at least $10" and for non-numeric entries we don't show anything.
