### ISSUE TITLE
Consider getting off XO, onto ESLint

### ISSUE THREAD

**Issue by osdiab** [everydotorg/donate-button#91]
The default configs are convenient but the VSCode plugin isn't as good and sometimes it wigs out hard, hasn't been updated for a year (https://github.com/SamVerschueren/vscode-linter-xo/issues/86). ESLint is a better development experience as of now, but more manual configuration.

**Comment by osdiab** [comment]
fine for now, lets revisit later

**Comment by sikhote** [comment]
The plugin is no longer available on vscode, so I guess not using XO anymore :(
