### ISSUE TITLE
options to React entrypoint should match global options configuration

### ISSUE THREAD

**Issue by osdiab** [everydotorg/donate-button#93]
necessary for #48 .

Right now you have to pass a full options configuration to the `EveryMonth` component (to be renamed), instead of just a partial one. We shouldn't be merging options in the loader script, it should be in the `EveryMonth` script

**Comment by martinbianchi** [comment]
@osdiab I want to check with you If I understand correctly. We should move [this code](https://github.com/everydotorg/donate-button/blob/8bd54f8a5d96fc70329f83e9c3e4363f0983bc8a/packages/donate-button/src/every-month-loader.tsx#L61) inside the `<EveryMonth />` component?

**Comment by osdiab** [comment]
yup!
