### ISSUE TITLE
Make a button, don't just attach to click handler

### ISSUE THREAD

**Issue by osdiab** [everydotorg/donate-button#98]
While we can continue to expose a function to just pop the modal via JavaScript as `show()` does now, the default UX in my opinion should be that we create the button on behalf of the client, to ensure that it works and feels right.

**Comment by martinbianchi** [comment]
@osdiab That's sound great! How do you think we should expose the button? I mean, maybe a  FAB fixed to the host page? Or expose a button that people can use adding some code in their pages?

**Comment by osdiab** [comment]
I'm thinking a couple ways:

- provide a selector to a div you wanna put the button in, and then render it there
	- perhaps a more foolproof option as well is to provide a copy-pastable chunk of code for people to paste wherever they want to put the button
- provide a react/preact component (more relevant once we have #48 )

Also relevant is #1 , but doesn't have to happen in a PR that implements this
